### PR TITLE
boot: zephyr: flash_map: Fix missing include

### LINKED ISSUE #2289: FLASH_ERASE_C_EXPLICIT define is not found
Hey all,

In `flash_map_backend.h` we have the following snippet

```
#if defined(CONFIG_MCUBOOT)
static inline bool flash_area_erase_required(const struct flash_area *fa)
{
#if defined(CONFIG_FLASH_HAS_EXPLICIT_ERASE) && defined(CONFIG_FLASH_HAS_NO_EXPLICIT_ERASE)
    const struct flash_parameters *fp = flash_get_parameters(flash_area_get_device(fa));

    return flash_params_get_erase_cap(flash_get_parameters(flash_area_get_device(fa))) &
            FLASH_ERASE_C_EXPLICIT;
#elif defined(CONFIG_FLASH_HAS_EXPLICIT_ERASE)
    return true;
#else
    return false;
#endif
}
#endif
```

When I build the app with both CONFIG_FLASH_HAS_EXPLICIT_ERASE and CONFIG_FLASH_HAS_NO_EXPLICIT_ERASE enabled I see

```
/Users/vanpetrosyan/Projects/scs-workspace/bootloader/mcuboot/boot/zephyr/include/flash_map_backend/flash_map_backend.h:117:13: error: 'FLASH_ERASE_C_EXPLICIT' undeclared (first use in this function)
  117 |             FLASH_ERASE_C_EXPLICIT;
```

Seems like we are missing  `FLASH_ERASE_C_EXPLICIT` define, which is defined in  `<zephyr/drivers/flash.h>`. When I add the file to the includes everything works.

### PR DESCRIPTION
**Pull request by nordicjm**
Adds an include file that is missing

Fixes #2289

### CODE REVIEW

File: boot/zephyr/include/flash_map_backend/flash_map_backend.h [hunk 1]
```diff
@@ -10,6 +10,10 @@
 
 #include <zephyr/storage/flash_map.h> // the zephyr flash_map
 
+#if defined(CONFIG_FLASH_HAS_EXPLICIT_ERASE) && defined(CONFIG_FLASH_HAS_NO_EXPLICIT_ERASE)
+#include <zephyr/storage/flash.h>
```
Comment (de-nordic) [inline boot/zephyr/include/flash_map_backend/flash_map_backend.h:14]:
```suggestion
#include <zephyr/drivers/flash.h>
```

**Comment by adigie** [comment]
@nordicjm could you also fix the unused `fp` variable in `flash_area_erase_required`?

File: boot/zephyr/include/flash_map_backend/flash_map_backend.h (hunk 1 above)
Comment (nordicjm) [reply boot/zephyr/include/flash_map_backend/flash_map_backend.h]: Fixed

File: boot/zephyr/include/flash_map_backend/flash_map_backend.h [hunk 2]
```diff
@@ -10,6 +10,10 @@
 
 #include <zephyr/storage/flash_map.h> // the zephyr flash_map
 
+#if defined(CONFIG_FLASH_HAS_EXPLICIT_ERASE) && defined(CONFIG_FLASH_HAS_NO_EXPLICIT_ERASE)
```
[the remark this answers is not in the document]
Comment (nordicjm) [reply boot/zephyr/include/flash_map_backend/flash_map_backend.h]: Changed

**Comment by nordicjm** [comment]
> @nordicjm could you also fix the unused `fp` variable in `flash_area_erase_required`?

Fixed

**Comment by adigie** [comment]
> > @nordicjm could you also fix the unused `fp` variable in `flash_area_erase_required`?
> 
> Fixed

This comment was about the `fp` declared after `#if defined...`. It should be something like:
```c
    const struct flash_parameters *fp = flash_get_parameters(flash_area_get_device(fa));
    return flash_params_get_erase_cap(fp) & FLASH_ERASE_C_EXPLICIT;
```

**Comment by nordicjm** [comment]
> > > @nordicjm could you also fix the unused `fp` variable in `flash_area_erase_required`?
> > 
> > 
> > Fixed
> 
> This comment was about the `fp` declared after `#if defined...`. It should be something like:
> 
> ```c
>     const struct flash_parameters *fp = flash_get_parameters(flash_area_get_device(fa));
>     return flash_params_get_erase_cap(fp) & FLASH_ERASE_C_EXPLICIT;
> ```

Indeed, removed temp. variable

**Review by de-nordic — APPROVED** [review]
