### PR TITLE
boot: bootutil: Fix serial recovery issues

### LINKED ISSUE #2360: mcuboot serial recovery wholly broken for single slot modes
The recent fix for image state null introduced code that calls various functions like `boot_open_all_flash_areas` which are added in loader.c, however, there's a bunch of MCUboot modes that do not use this file e.g. single slot, single ram load mode so when you configure MCUboot in one of these mode with serial recovery mode, you get the following:

```
/opt/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/libzephyr.a(boot_serial.c.obj): in function `bs_list_set':
/tmp/cc/bootloader/mcuboot/boot/boot_serial/src/boot_serial.c:657: undefined reference to `boot_state_clear'
/opt/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: /tmp/cc/bootloader/mcuboot/boot/boot_serial/src/boot_serial.c:659: undefined reference to `boot_open_all_flash_areas'
/opt/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: /tmp/cc/bootloader/mcuboot/boot/boot_serial/src/boot_serial.c:670: undefined reference to `boot_read_sectors'
/opt/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: /tmp/cc/bootloader/mcuboot/boot/boot_serial/src/boot_serial.c:691: undefined reference to `boot_close_all_flash_areas'
/opt/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: /tmp/cc/bootloader/mcuboot/boot/boot_serial/src/boot_serial.c:691: undefined reference to `boot_close_all_flash_areas'
/opt/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: /tmp/cc/bootloader/mcuboot/boot/boot_serial/src/boot_serial.c:691: undefined reference to `boot_close_all_flash_areas'
collect2: error: ld returned 1 exit status
```

### PR DESCRIPTION
**Pull request by nordicjm**
Fixes serial recovery issues in various MCUboot operating modes by moving functions that are needed out from loader to a common file and adapting them to work in these different modes

Fixes #2360

### CODE REVIEW

File: boot/zephyr/single_loader.c [hunk 1]
```diff
@@ -118,16 +189,13 @@ boot_go(struct boot_rsp *rsp)
 
     BOOT_LOG_DBG("boot_go: Single loader");
 
-    rc = flash_area_open(FLASH_AREA_IMAGE_PRIMARY(0), &_fa_p);
-    assert(rc == 0);
+    rc = boot_open_all_flash_areas(&state);
```
Comment (de-nordic) [inline boot/zephyr/single_loader.c:192]: Shouldn't we follow this with at least `assert(rc == 0`?

**Review by de-nordic — APPROVED** [review]

File: boot/zephyr/single_loader.c (hunk 1 above)
Comment (nordicjm) [reply boot/zephyr/single_loader.c:192]: it's already handled in the open function:
```
    rc = flash_area_open(FLASH_AREA_IMAGE_PRIMARY(0), &BOOT_IMG_AREA(state, BOOT_PRIMARY_SLOT));
    assert(rc == 0);
```
