### PR TITLE
loader: Allow image header bigger than 1 KB for encrypted images

### LINKED ISSUE #1191: Possible size overflow for header block size in image encryption
**Issue:**

I am using MCUboot with Zephyr, and set a header size of 0x1000. In `loader:boot_copy_region`, this leads to a chunk size of 0x400 (buffer size). If on start of the image (`loader.c:907`), this leads to a silent overflow in `blk_sz` on line 910.

Interesting code:
`blk_sz = chunk_sz - hdr->ih_hdr_size; // chunk_sz = 0x400; hdr->ih_hdr_size = 0x1000`.

**Suggested fix:**

1. Check for this overflow, return `BOOT_EBADARGS`
2. imgtool should check for meaningful values of the header size.

### LINKED ISSUE #1200: RSA decryption key can't be loaded due to mbedtls_rsa_rsaes_oaep_decrypt() error
I tested encryption with zephyr-rtos and mbedtls 3.0.0

west build -d build/xd -b nrf52840dk_nrf52840 bootloader/mcuboot/boot/zephyr -- -DCONFIG_BOOT_ENCRYPT_RSA=y -DCONFIG_BOOT_BOOTSTRAP=y

RSA decryption is failing due to error in encryption key decryption.
call to mbedtls_rsa_rsaes_oaep_decrypt() from boot_enc_decrypt() returns erorcode -0x4310

This is regression in compression to mbedtls 2.7.0 usage

### PR DESCRIPTION
**Pull request by nvlsianpu**
boot_copy_region() was written so it assumes that the image header
must fit int the intermediary buffer of 1 KB size. A bigger header
will cause a overflow in calculation of size of data chunk to be
decrypted.

This patch allow to use header bigger than that buffer size and
mitigate the limitation described above.

This patch was tested on zephyr nrf52840dk_nrf52840 with image headed size increased to 0x600.
It was done by simple modification i zephyr's Kconfig.zephyr file:

```Kconfig
config ROM_START_OFFSET
	hex
	prompt "ROM start offset" if !BOOTLOADER_MCUBOOT
	default 0x600 if BOOTLOADER_MCUBOOT # <-was 0x200
	default 0
	help
```

fixes #1191
fixes #1200

### CODE REVIEW

**Comment by nvlsianpu** [comment]
@d3zd3z for zephyr `mbedtls/library` directory must be added to inclusion directories in order to make RSA encryption working. This is regression after zephyr has switched to MBTLS 3.0.0 I will open fix to zephyr.

**Comment by nvlsianpu** [comment]
^^ https://github.com/zephyrproject-rtos/zephyr/pull/40092 fixes the build

**Comment by d3zd3z** [comment]
There is a typo in the commit text of the middle patch, fies -> fixes. Although, I think having the text in the description of the PR will be sufficient to close the issue.

File: boot/bootutil/src/encrypted.c [hunk 1]
```diff
@@ -15,7 +15,11 @@
 #if defined(MCUBOOT_ENCRYPT_RSA)
 #include "mbedtls/rsa.h"
 #if MBEDTLS_VERSION_NUMBER >= 0x03000000
+#ifdef __ZEPHYR__
+#include "mbedtls/../../library/rsa_alt_helpers.h"
```
Comment (d3zd3z) [inline boot/bootutil/src/encrypted.c:19]: Hmm, not sure I like this. Is it possible to add something to the Cmake file regarding this file to specifically add to the include path but only when compiling this file. (maybe set_source_files_properties)?

File: boot/zephyr/os.c [hunk 2]
```diff
@@ -41,7 +41,7 @@
 #define CRYPTO_HEAP_SIZE 6144
 #else
 #  if !defined(MBEDTLS_RSA_NO_CRT)
-#  define CRYPTO_HEAP_SIZE 10240
+#  define CRYPTO_HEAP_SIZE 12032//11860
```
Comment (d3zd3z) [inline boot/zephyr/os.c:44]: This is kind of confusing, with the comment butted up like that. Maybe just have 12032?

**Review by d3zd3z — CHANGES_REQUESTED** [review]

File: boot/bootutil/src/encrypted.c (hunk 1 above)
Comment (nvlsianpu) [reply boot/bootutil/src/encrypted.c:19]: @tejlmand Can you help with that?

Comment (nvlsianpu) [reply boot/bootutil/src/encrypted.c:19]: Following syntax works fine indeed.
``` Cmake
  set_source_files_properties(${BOOT_DIR}/bootutil/src/encrypted.c
  PROPERTIES
  INCLUDE_DIRECTORIES ${ZEPHYR_BASE}/../modules/crypto/mbedtls/library)
```

File: boot/zephyr/os.c (hunk 2 above)
Comment (nvlsianpu) [reply boot/zephyr/os.c:44]: ops, post investigation artefact :)  commented value was the lowers seams to working.
I rounded it up to multiplication of 0x100.

File: boot/zephyr/CMakeLists.txt [hunk 3]
```diff
@@ -191,6 +191,11 @@ elseif(CONFIG_BOOT_SIGNATURE_TYPE_RSA)
   # Use mbedTLS provided by Zephyr for RSA signatures. (Its config file
   # is set using Kconfig.)
   zephyr_include_directories(include)
+  if(CONFIG_BOOT_ENCRYPT_RSA)
+    set_source_files_properties(${BOOT_DIR}/bootutil/src/encrypted.c
+    PROPERTIES
```
Comment (d3zd3z) [inline boot/zephyr/CMakeLists.txt:196]: Sorry for the nit pick, but I think this will look better with these additional lines indented, otherwise they look more like additional top-level commands). I think the indentation just got dropped from the comment.

**Comment by d3zd3z** [comment]
See #1203 to track adding sim support to catch this kind of issue earlier.

File: boot/bootutil/src/loader.c [hunk 4]
```diff
@@ -961,28 +961,39 @@ boot_copy_region(struct boot_loader_state *state,
...
 #endif
             if (IS_ENCRYPTED(hdr)) {
-                blk_sz = chunk_sz;
-                idx = 0;
                 if (off + bytes_copied < hdr->ih_hdr_size) {
                     /* do not decrypt header */
-                    blk_off = 0;
-                    blk_sz = chunk_sz - hdr->ih_hdr_size;
-                    idx = hdr->ih_hdr_size;
+                    if (off + bytes_copied + chunk_sz > hdr->ih_hdr_size) {
```
Comment (de-nordic) [inline boot/bootutil/src/loader.c:966]: The `off + bytes_copied` keeps on repeating maybe it could be aliased.

File: boot/bootutil/src/loader.c [hunk 5]
```diff
@@ -961,28 +961,39 @@ boot_copy_region(struct boot_loader_state *state,
...
+                        /* The lower part of the chunk contains header data */
+                        blk_off = 0;
+                        blk_sz = chunk_sz - (hdr->ih_hdr_size - off -
+                                 bytes_copied);
+                        idx = hdr->ih_hdr_size  - off - bytes_copied;
```
Comment (de-nordic) [inline boot/bootutil/src/loader.c:971]: If you turn around the lines then:
```
blk_sz = chunk_sz - idx;
```

**Review by d3zd3z — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]
Left some comments regarding repeating arithmetic expressions.

Nevertheless, it looks OK.

**Review by de-nordic — APPROVED** [review]
