### PR TITLE
fix build with encryption enabled after bootutil_publi library was introduced

### LINKED ISSUE #938: Cannot build encrypted images on Zephyr
Building with rsa-oaep:

```
west build -b nrf52840dk_nrf52840 -d build_boot bootloader/mcuboot/boot/zephyr -- -DCONFIG_BOOT_ENCRYPT_RSA=y
```
results in:

```
...
In file included from /home/utzig/src/Nordic/mcuboot/boot/bootutil/zephyr/../include/bootutil/enc_key.h:33,
                 from /home/utzig/src/Nordic/mcuboot/boot/bootutil/src/bootutil_priv.h:43,
                 from /home/utzig/src/Nordic/mcuboot/boot/bootutil/src/bootutil_public.c:48:
/home/utzig/src/Nordic/mcuboot/boot/bootutil/zephyr/../include/bootutil/crypto/aes_ctr.h:23:14: fatal error: mbedtls/aes.h: No such file or directory
   23 |     #include <mbedtls/aes.h>
      |              ^~~~~~~~~~~~~~~
compilation terminated.
```

Building with ec256:

```
west build -b nrf52840dk_nrf52840 -d build_boot bootloader/mcuboot/boot/zephyr -- -DCONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y -DCONFIG_BOOT_ENCRYPT_EC256=y
```
results in:

```
...
In file included from /home/utzig/src/Nordic/mcuboot/boot/bootutil/zephyr/../include/bootutil/enc_key.h:33,
                 from /home/utzig/src/Nordic/mcuboot/boot/bootutil/src/bootutil_priv.h:43,
                 from /home/utzig/src/Nordic/mcuboot/boot/bootutil/src/bootutil_public.c:48:
/home/utzig/src/Nordic/mcuboot/boot/bootutil/zephyr/../include/bootutil/crypto/aes_ctr.h:30:14: fatal error: tinycrypt/aes.h: No such file or directory
   30 |     #include <tinycrypt/aes.h>
      |              ^~~~~~~~~~~~~~~~~
compilation terminated.
```

This fails since bootutil was separated into a public part. I belive it stems from the bootutil_public.c CMakeLists.txt not adding the proper include paths, which is only required by bootutil_priv.h. Eg, I was able to fix EC256 with the following diff:

```diff
--- a/boot/bootutil/zephyr/CMakeLists.txt
+++ b/boot/bootutil/zephyr/CMakeLists.txt
@@ -12,6 +12,10 @@ target_include_directories(MCUBOOT_BOOTUTIL INTERFACE
   ../../zephyr/include
 )
 
+if(CONFIG_BOOT_ENCRYPT_EC256)
+  zephyr_include_directories(../../../ext/tinycrypt/lib/include)
+endif()
+
 zephyr_library()
 zephyr_library_sources(
   ../src/bootutil_public.c
```

### PR DESCRIPTION
**Pull request by nvlsianpu**
fixes #938

### CODE REVIEW

File: boot/bootutil/src/bootutil_public.c [hunk 1]
```diff
@@ -36,6 +36,7 @@
  * which controls DFU process.
  */
 
+
```
Comment (utzig) [inline boot/bootutil/src/bootutil_public.c:39]: You can remove this extra empty line.

**Review by utzig — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]
